#! /usr/bin/env node
const fs = require("fs");
const shell = require("shelljs");
const chalk = require("chalk");
const package = require("./package.json");
const isGitDirty = require("is-git-dirty");

const run = () => {
  if (isGitDirty()) {
    console.log(
      chalk.red(
        "\n\n 😈Looks like you have uncommitted git changes. You should commit these first, and then run this again. 🙃💆\n\n"
      )
    );
    return;
  }
  console.log(
    chalk.cyan(
      "\n\n",
      package.name,
      "Started! Version: ",
      package.version,
      "\n\n"
    )
  );
  console.log(chalk.blue("\n\nInstalling eslint-config-nando ⚡️😷🦸‍♂️.\n\n"));
  shell.exec("yarn add -D eslint-config-nando");
  console.log(chalk.green("\n\nEslint installed.👰\n\n"));
  console.log(chalk.blue("\n\nWriting lint files.\n\n"));
  fs.writeFileSync(
    ".eslintrc",
    `
// generated by @nandorojo/lint-expo 
{"extends": ["nando"]}`
  );
  fs.writeFileSync(
    ".prettierrc.js",
    `
// generated by @nandorojo/lint-expo 
module.exports = require('eslint-config-nando/prettier')`
  );
  console.log(
    chalk.green(
      "\n\n👀 Your app is successfully linted. Files created: [.prettierrc.js, .eslintrc] 🧹\n\n"
    )
  );
};

run();
